{{- $secretName := print (include "patroni.fullname" .) "-appusers" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- $index := 1 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "patroni.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.additionalCredentials }}
  {{- $user := print "appuser" $index }}
  {{- if $secret }}
  username-{{ $user }}: {{ index $secret.data (print "username-" $user) }}
  password-{{ $user }}: {{ index $secret.data (print "password-" $user) }}
  {{- else }}
  username-{{ $user }}: {{ $value.username | b64enc }}
  password-{{ $user }}: {{ $value.password | default (randAlphaNum 32) | b64enc }}
  {{- end }}
  {{ $index = add1 $index }}
  {{- end }}
