{{- $secretName := print (include "patroni.fullname" .) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}

{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "patroni.labels" . | nindent 4 }}
type: Opaque
data:
  username-superuser: {{ .Values.credentials.superuser.username | b64enc }}
  username-admin: {{ .Values.credentials.admin.username | b64enc }}
  username-standby: {{ .Values.credentials.standby.username | b64enc }}
  {{- if $secret }}
  password-superuser: {{ index $secret.data "password-superuser" }}
  password-admin: {{ index $secret.data "password-admin" }}
  password-standby: {{ index $secret.data "password-standby" }}
  {{- else }}
  password-superuser: {{ .Values.credentials.superuser.password | default (randAlphaNum 32) | b64enc }}
  password-admin: {{ .Values.credentials.admin.password | default (randAlphaNum 32) | b64enc }}
  password-standby: {{ .Values.credentials.standby.password | default (randAlphaNum 32) | b64enc }}
  {{- end }}
{{- end }}
