{{- if .Values.maintenancePage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sso-keycloak.fullname" . }}-maintenance
  labels: {{ include "sso-keycloak.maintenanceLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.maintenancePage.replicaCount }}
  selector:
    matchLabels: {{ include "sso-keycloak.maintenanceSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "sso-keycloak.maintenanceLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-maintenance
          image: "{{ .Values.maintenancePage.image.repository }}:{{ .Values.maintenancePage.image.tag }}"
          imagePullPolicy: {{ .Values.maintenancePage.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.maintenancePage.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
