{{- $adminSecretName := (printf "%s-admin" (include "sso-keycloak.fullname" .)) }}
{{- $adminSecret := (lookup "v1" "Secret" .Release.Namespace $adminSecretName ) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $adminSecretName }}
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $adminSecret }}
  username: {{ index $adminSecret.data "username" }}
  password: {{ index $adminSecret.data "password" }}
  {{- else }}
  username: {{ .Values.admin.username | default (randAlphaNum 8) | b64enc }}
  password: {{ .Values.admin.password | default (randAlphaNum 32) | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sso-keycloak.fullname" . }}-jgroups
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  cluster-password: {{ randAlphaNum 32 | b64enc | quote }}
