{{- if .Values.maintenancePage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sso-keycloak.fullname" . }}-maintenance
  labels: {{ include "sso-keycloak.maintenanceLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: http
  selector: {{ include "sso-keycloak.maintenanceSelectorLabels" . | nindent 4 }}
{{- end }}
