apiVersion: v1
kind: Service
metadata:
  name: {{ include "metabase.fullname" . }}
  labels: {{ include "metabase.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end}}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "metabase.selectorLabels" . | nindent 4 }}
