{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "patroni.fullname" . }}
  labels: {{ include "patroni.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "patroni.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "patroni.fullname" . }}
{{- end }}
