{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "patroni.serviceAccountName" . }}
  labels: {{ include "patroni.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  affinity: {{ .Values.affinity | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
