apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.fullname" . }}
  labels: {{ include "patroni.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector: {{ include "patroni.selectorLabels" . | nindent 4 }}
    {{ .Values.kubernetes.roleLabel }}: master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "patroni.fullname" . }}-readonly
  labels: {{ include "patroni.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector: {{ include "patroni.selectorLabels" . | nindent 4 }}
    {{ .Values.kubernetes.roleLabel }}: replica
